### ISSUE TITLE
Can't run tokenizer

### ISSUE THREAD

**Issue by plusInfinity** [JohannesVod/Alilama#1]
Hi!

I am trying to run `data/TokenizeData.py` and I am getting the following error:
```
Traceback (most recent call last):
  File "/home/sasha/ML_DS/ML Research/Alilama/data/TokenizeData.py", line 5, in <module>
    from tokenizer import RegexTokenizer
  File "/home/sasha/ML_DS/ML Research/Alilama/data/tokenizer/__init__.py", line 2, in <module>
    from .regex import RegexTokenizer
  File "/home/sasha/ML_DS/ML Research/Alilama/data/tokenizer/regex.py", line 13, in <module>
    from .fastfuncs.funcs import trainFast, tokenizeFast
ImportError: dynamic module does not define module export function (PyInit_funcs)
```

I wonder if you know what might cause it. Googling quickly the error didn't help.

**Comment by JohannesVod** [comment]
make sure you are in the root directory. I think then it should work

**Comment by JohannesVod** [comment]
I am not really sure. I tried it again on my pc and it does work. Make sure to be in the root directory and then execute 
`python data/TokenizeData.py`
You can also try to cd into the data folder and execute it directly, this also works on my pc. Let me know if this helps. If not there might be something wrong with the repo

**Comment by plusInfinity** [comment]
Thank you for looking into it! This might be something Linux-specific or due to an incompatible version of Cython I have. Here is a quick way to reproduce the issue in a colab notebook: https://colab.research.google.com/drive/17w3TKkQtfJpU9hfD_GemkxtShTeQn4ih

I tried recompiling with `g++ -fpic -shared -O3 -o funcs.so funcs.cpp -static-libstdc++` but this didn't help.

I have python3.11, cython==3.0.9 and numpy==1.26.4

**Comment by JohannesVod** [comment]
Alright, i will take a look at it. It is probably something linux specific. I developed under windows and only tested on linux using WSL

**Comment by JohannesVod** [comment]
Ok, i fixed the issue. I just had to rename the .so file. Let me know if it works now

**Comment by plusInfinity** [comment]
Thanks, it works now! BTW thank you for sharing your work here. I was looking for a bit more modern analogs of nanoGPT to play with and was lucky to stumble on your blog post and the repo.

**Comment by plusInfinity** [comment]
Thanks, it works now! BTW thank you for sharing your work here. I was looking for a bit more modern analogs of nanoGPT to play with and was lucky to stumble on your blog post and the repo.
